/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package my.ageofsettlers;

/**
 *
 * @author Tim
 */
public class attackHoldingAreaGUI extends javax.swing.JFrame {

    /**
     * Creates new form attackHoldingAreaGUI
     */
    public attackHoldingAreaGUI() {
        this.board = BoardController.getInstance();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        playerFoodText = new javax.swing.JTextField();
        playerFoodSelection = new javax.swing.JComboBox();
        playerFavorText = new javax.swing.JTextField();
        playerFavorSelection = new javax.swing.JComboBox();
        playerWoodText = new javax.swing.JTextField();
        playerWoodSelection = new javax.swing.JComboBox();
        playerGoldText = new javax.swing.JTextField();
        playerGoldSelection = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255,255,255,1));
        jTextField1.setText("Select 5 resources to steal:");
        jTextField1.setBorder(null);

        playerFoodText.setEditable(false);
        playerFoodText.setBackground(new java.awt.Color(255,255,255,1));
        playerFoodText.setText("Food:");
        playerFoodText.setBorder(null);

        playerFoodSelection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        playerFavorText.setEditable(false);
        playerFavorText.setBackground(new java.awt.Color(255,255,255,1));
        playerFavorText.setText("Favor:");
        playerFavorText.setBorder(null);

        playerFavorSelection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        playerWoodText.setEditable(false);
        playerWoodText.setBackground(new java.awt.Color(255,255,255,1));
        playerWoodText.setText("Wood:");
        playerWoodText.setBorder(null);

        playerWoodSelection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        playerGoldText.setEditable(false);
        playerGoldText.setBackground(new java.awt.Color(255,255,255,1));
        playerGoldText.setText("Gold:");
        playerGoldText.setBorder(null);

        playerGoldSelection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Steal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(playerFoodText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(playerFoodSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(playerFavorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(playerFavorSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(jButton1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(playerWoodText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(playerWoodSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(playerGoldText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(playerGoldSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(playerFoodText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(playerFoodSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(playerFavorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(playerFavorSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(playerWoodText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(playerWoodSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(playerGoldText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(playerGoldSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(28, 28, 28))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int playerFoodCount = Integer.parseInt((String)playerFoodSelection.getSelectedItem());
        int playerFavorCount = Integer.parseInt((String)playerFavorSelection.getSelectedItem());
        int playerWoodCount = Integer.parseInt((String)playerWoodSelection.getSelectedItem());
        int playerGoldCount = Integer.parseInt((String)playerGoldSelection.getSelectedItem());

        int sum1 = playerFoodCount + playerFavorCount + playerWoodCount + playerGoldCount;
        int sum2 = 5;

        if(sum1 == sum2) {
            if(attacker.compareTo("Norse") == 0) {
                Norse norsePlayer = Norse.getInstance();
                norsePlayer.setFood(norsePlayer.getFood() + playerFoodCount);
                norsePlayer.setFavor(norsePlayer.getFavor() + playerFavorCount);
                norsePlayer.setWood(norsePlayer.getWood() + playerWoodCount);
                norsePlayer.setGold(norsePlayer.getGold() + playerGoldCount);
            }
            else if(attacker.compareTo("Greek") == 0) {
                Greek greekPlayer = Greek.getInstance();
                greekPlayer.setFood(greekPlayer.getFood() + playerFoodCount);
                greekPlayer.setFavor(greekPlayer.getFavor() + playerFavorCount);
                greekPlayer.setWood(greekPlayer.getWood() + playerWoodCount);
                greekPlayer.setGold(greekPlayer.getGold() + playerGoldCount);
            }
            else {
                Egyptian egyptianPlayer = Egyptian.getInstance();
                egyptianPlayer.setFood(egyptianPlayer.getFood() + playerFoodCount);
                egyptianPlayer.setFavor(egyptianPlayer.getFavor() + playerFavorCount);
                egyptianPlayer.setWood(egyptianPlayer.getWood() + playerWoodCount);
                egyptianPlayer.setGold(egyptianPlayer.getGold() + playerGoldCount);
            }

            if(defender.compareTo("Norse") == 0) {
                Norse norsePlayer = Norse.getInstance();
                norsePlayer.setFood(norsePlayer.getFood() - playerFoodCount);
                norsePlayer.setFavor(norsePlayer.getFavor() - playerFavorCount);
                norsePlayer.setWood(norsePlayer.getWood() - playerWoodCount);
                norsePlayer.setGold(norsePlayer.getGold() - playerGoldCount);
            }
            else if(defender.compareTo("Greek") == 0) {
                Greek greekPlayer = Greek.getInstance();
                greekPlayer.setFood(greekPlayer.getFood() - playerFoodCount);
                greekPlayer.setFavor(greekPlayer.getFavor() - playerFavorCount);
                greekPlayer.setWood(greekPlayer.getWood() - playerWoodCount);
                greekPlayer.setGold(greekPlayer.getGold() - playerGoldCount);
            }
            else {
                Egyptian egyptianPlayer = Egyptian.getInstance();
                egyptianPlayer.setFood(egyptianPlayer.getFood() - playerFoodCount);
                egyptianPlayer.setFavor(egyptianPlayer.getFavor() - playerFavorCount);
                egyptianPlayer.setWood(egyptianPlayer.getWood() - playerWoodCount);
                egyptianPlayer.setGold(egyptianPlayer.getGold() - playerGoldCount);
            }
            
            board.updateResources(attacker);
            board.updateResources(defender);
            this.setVisible(false);
            board.initPlayPermCards();
        }
        else {
            attackHoldingAreaErrorGUI ahaeGUI = new attackHoldingAreaErrorGUI();
            ahaeGUI.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        board.initPlayPermCards();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(attackHoldingAreaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(attackHoldingAreaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(attackHoldingAreaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(attackHoldingAreaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new attackHoldingAreaGUI().setVisible(true);
            }
        });
    }

    public void setupHoldingAreaGUI(String attacker, String defender) {
        String[] foodCount;
        String[] favorCount;
        String[] woodCount;
        String[] goldCount;
        
        this.attacker = attacker;
        this.defender = defender;
        
        if(defender.compareTo("Norse") == 0) {
            Norse norsePlayer = Norse.getInstance();
            foodCount = new String[norsePlayer.getFood()+1];
            favorCount = new String[norsePlayer.getFavor()+1];
            woodCount = new String[norsePlayer.getWood()+1];
            goldCount = new String[norsePlayer.getGold()+1];
        }
        else if(defender.compareTo("Greek") == 0) {
            Greek greekPlayer = Greek.getInstance();
            foodCount = new String[greekPlayer.getFood()+1];
            favorCount = new String[greekPlayer.getFavor()+1];
            woodCount = new String[greekPlayer.getWood()+1];
            goldCount = new String[greekPlayer.getGold()+1];
        }
        else {
            Egyptian egyptianPlayer = Egyptian.getInstance();
            foodCount = new String[egyptianPlayer.getFood()+1];
            favorCount = new String[egyptianPlayer.getFavor()+1];
            woodCount = new String[egyptianPlayer.getWood()+1];
            goldCount = new String[egyptianPlayer.getGold()+1];
        }
        
        for(int i = 0; i < foodCount.length; i++) {
            foodCount[i] = String.valueOf(i);
        }
        playerFoodSelection.setModel(new javax.swing.DefaultComboBoxModel(foodCount));
        for(int i = 0; i < favorCount.length; i++) {
            favorCount[i] = String.valueOf(i);
        }
        playerFavorSelection.setModel(new javax.swing.DefaultComboBoxModel(favorCount));
        for(int i = 0; i < woodCount.length; i++) {
            woodCount[i] = String.valueOf(i);
        }
        playerWoodSelection.setModel(new javax.swing.DefaultComboBoxModel(woodCount));
        for(int i = 0; i < goldCount.length; i++) {
           goldCount[i] = String.valueOf(i);
        }
        playerGoldSelection.setModel(new javax.swing.DefaultComboBoxModel(goldCount));
    }
    
    private String attacker;
    private String defender;
    private BoardController board;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox playerFavorSelection;
    private javax.swing.JTextField playerFavorText;
    private javax.swing.JComboBox playerFoodSelection;
    private javax.swing.JTextField playerFoodText;
    private javax.swing.JComboBox playerGoldSelection;
    private javax.swing.JTextField playerGoldText;
    private javax.swing.JComboBox playerWoodSelection;
    private javax.swing.JTextField playerWoodText;
    // End of variables declaration//GEN-END:variables
}
