/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package my.ageofsettlers;

/**
 *
 * @author Tim
 */
public class gatherGUI extends javax.swing.JFrame {

    /**
     * Creates new form gatherGUI
     */
    public gatherGUI() {
        this.board = BoardController.getInstance();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        Fertile = new javax.swing.JRadioButton();
        Forest = new javax.swing.JRadioButton();
        Desert = new javax.swing.JRadioButton();
        Hills = new javax.swing.JRadioButton();
        Swamp = new javax.swing.JRadioButton();
        Mountain = new javax.swing.JRadioButton();
        Wood = new javax.swing.JRadioButton();
        Food = new javax.swing.JRadioButton();
        Gold = new javax.swing.JRadioButton();
        Favor = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255,255,255,1));
        jTextField1.setText("Select an option to gather from:");
        jTextField1.setBorder(null);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        buttonGroup2.add(Fertile);
        Fertile.setText("Fertile");
        jPanel1.add(Fertile, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        buttonGroup2.add(Forest);
        Forest.setText("Forest");
        jPanel1.add(Forest, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        buttonGroup2.add(Desert);
        Desert.setText("Desert");
        jPanel1.add(Desert, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        buttonGroup2.add(Hills);
        Hills.setText("Hills");
        jPanel1.add(Hills, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        buttonGroup2.add(Swamp);
        Swamp.setText("Swamp");
        jPanel1.add(Swamp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        buttonGroup2.add(Mountain);
        Mountain.setText("Mountain");
        jPanel1.add(Mountain, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        buttonGroup2.add(Wood);
        Wood.setText("Wood");
        jPanel1.add(Wood, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        buttonGroup2.add(Food);
        Food.setText("Food");
        jPanel1.add(Food, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        buttonGroup2.add(Gold);
        Gold.setText("Gold");
        jPanel1.add(Gold, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        buttonGroup2.add(Favor);
        Favor.setText("Favor");
        jPanel1.add(Favor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String str = "";
        if(Desert.isSelected() == true) {
            str = "desert";
        }
        else if(Fertile.isSelected() == true) {
            str = "fertile";
        }
        else if(Hills.isSelected() == true) {
            str = "hill";
        }
        else if(Forest.isSelected() == true) {
            str = "forest";
        }
        else if(Mountain.isSelected() == true) {
            str = "mountain";
        }
        else if(Swamp.isSelected() == true) {
            str = "swamp";
        }
        else if(Favor.isSelected() == true) {
            str = "favor";
        }
        else if(Food.isSelected() == true) {
            str = "food";
        }
        else if(Wood.isSelected() == true) {
            str = "wood";
        }
        else {
            str = "gold";
        }
        
        board.playGatherCard(str, board.getPlayerCulture());
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gatherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gatherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gatherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gatherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gatherGUI().setVisible(true);
            }
        });
    }

    private BoardController board;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Desert;
    private javax.swing.JRadioButton Favor;
    private javax.swing.JRadioButton Fertile;
    private javax.swing.JRadioButton Food;
    private javax.swing.JRadioButton Forest;
    private javax.swing.JRadioButton Gold;
    private javax.swing.JRadioButton Hills;
    private javax.swing.JRadioButton Mountain;
    private javax.swing.JRadioButton Swamp;
    private javax.swing.JRadioButton Wood;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
