/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package my.ageofsettlers;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Tim
 */
public class PermanentCardsGUI extends javax.swing.JFrame {

    /**
     * Creates new form PermanentCardsGUI
     */
    public PermanentCardsGUI() {
        this.board = BoardController.getInstance();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PermanentAttack = new javax.swing.JPanel();
        attackMarked = new javax.swing.JLabel();
        attackMarked.setVisible(false);
        PermanentAttack_img = new javax.swing.JLabel();
        PermanentBuild = new javax.swing.JPanel();
        buildMarked = new javax.swing.JLabel();
        buildMarked.setVisible(false);
        PermanentBuild_img = new javax.swing.JLabel();
        PermanentGather = new javax.swing.JPanel();
        gatherMarked = new javax.swing.JLabel();
        gatherMarked.setVisible(false);
        PermanentGather_img = new javax.swing.JLabel();
        PermanentExplore = new javax.swing.JPanel();
        exploreMarked = new javax.swing.JLabel();
        exploreMarked.setVisible(false);
        PermanentExplore_img = new javax.swing.JLabel();
        PermanentNextAge = new javax.swing.JPanel();
        nextAgeMarked = new javax.swing.JLabel();
        nextAgeMarked.setVisible(false);
        PermanentNextAge_img = new javax.swing.JLabel();
        PermanentTrade = new javax.swing.JPanel();
        tradeMarked = new javax.swing.JLabel();
        tradeMarked.setVisible(false);
        PermanentTrade_img = new javax.swing.JLabel();
        PermanentRecruit = new javax.swing.JPanel();
        recruitMarked = new javax.swing.JLabel();
        recruitMarked.setVisible(false);
        PermanentRecruit_img = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PermanentAttack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        attackMarked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Marking.png"))); // NOI18N
        PermanentAttack.add(attackMarked, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 125, 125));

        PermanentAttack_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PermanentAttack_imgMouseClicked(evt);
            }
        });
        PermanentAttack.add(PermanentAttack_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 225));

        PermanentBuild.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buildMarked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Marking.png"))); // NOI18N
        PermanentBuild.add(buildMarked, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 125, 125));

        PermanentBuild_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PermanentBuild_imgMouseClicked(evt);
            }
        });
        PermanentBuild.add(PermanentBuild_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 225));

        PermanentGather.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gatherMarked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Marking.png"))); // NOI18N
        PermanentGather.add(gatherMarked, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 125, 125));

        PermanentGather_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PermanentGather_imgMouseClicked(evt);
            }
        });
        PermanentGather.add(PermanentGather_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 225));

        PermanentExplore.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exploreMarked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Marking.png"))); // NOI18N
        PermanentExplore.add(exploreMarked, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 125, 125));

        PermanentExplore_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PermanentExplore_imgMouseClicked(evt);
            }
        });
        PermanentExplore.add(PermanentExplore_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 225));

        PermanentNextAge.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nextAgeMarked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Marking.png"))); // NOI18N
        PermanentNextAge.add(nextAgeMarked, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 125, 125));

        PermanentNextAge_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PermanentNextAge_imgMouseClicked(evt);
            }
        });
        PermanentNextAge.add(PermanentNextAge_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 225));

        PermanentTrade.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tradeMarked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Marking.png"))); // NOI18N
        PermanentTrade.add(tradeMarked, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 125, 125));

        PermanentTrade_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PermanentTrade_imgMouseClicked(evt);
            }
        });
        PermanentTrade.add(PermanentTrade_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 225));

        PermanentRecruit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        recruitMarked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Marking.png"))); // NOI18N
        PermanentRecruit.add(recruitMarked, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 125, 125));

        PermanentRecruit_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PermanentRecruit_imgMouseClicked(evt);
            }
        });
        PermanentRecruit.add(PermanentRecruit_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 225));

        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PermanentAttack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PermanentBuild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PermanentGather, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PermanentExplore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PermanentNextAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PermanentTrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PermanentRecruit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton1)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PermanentRecruit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PermanentTrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PermanentNextAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PermanentExplore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PermanentGather, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PermanentBuild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PermanentAttack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, -1));
        setupCards();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        List<String> actionList = new ArrayList<>();
        if(attackMarked.isVisible() == true) {
            actionList.add("attack");
        }
        if(buildMarked.isVisible() == true) {
            actionList.add("build");
        }
        if(exploreMarked.isVisible() == true) {
            actionList.add("explore");
        }
        if(nextAgeMarked.isVisible() == true) {
            actionList.add("nextAge");
        }
        if(recruitMarked.isVisible() == true) {
            actionList.add("recruit");
        }
        if(tradeMarked.isVisible() == true) {
            actionList.add("trade");
        }
        if(gatherMarked.isVisible() == true) {
            actionList.add("gather");
        }
        
        board.setPlayerPermCards(actionList);
        board.initPlayPermCards();
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PermanentAttack_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PermanentAttack_imgMouseClicked
        if(attackMarked.isVisible() == false) {
            if(count < maxCards) {
                attackMarked.setVisible(true);
                count++;
            }
        }
        else {
            attackMarked.setVisible(false);
            count--;
        }
    
    }//GEN-LAST:event_PermanentAttack_imgMouseClicked

    private void PermanentBuild_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PermanentBuild_imgMouseClicked
        if(buildMarked.isVisible() == false) {
            if(count < maxCards) {
                buildMarked.setVisible(true);
                count++;
            }
        }
        else {
            buildMarked.setVisible(false);
            count--;
        }
    }//GEN-LAST:event_PermanentBuild_imgMouseClicked

    private void PermanentGather_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PermanentGather_imgMouseClicked
        if(gatherMarked.isVisible() == false && count <= maxCards) {
            if(count < maxCards) {
                gatherMarked.setVisible(true);
                count++;
            }
        }
        else {
            gatherMarked.setVisible(false);
            count--;
        }
    }//GEN-LAST:event_PermanentGather_imgMouseClicked

    private void PermanentExplore_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PermanentExplore_imgMouseClicked
        if(exploreMarked.isVisible() == false) {
            if(count < maxCards) {
                exploreMarked.setVisible(true);
                count++;
            }
        }
        else {
            exploreMarked.setVisible(false);
            count--;
        }
    }//GEN-LAST:event_PermanentExplore_imgMouseClicked

    private void PermanentNextAge_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PermanentNextAge_imgMouseClicked
        if(nextAgeMarked.isVisible() == false) {
            if(count < maxCards) {
                nextAgeMarked.setVisible(true);
                count++;
            }
        }
        else {
            nextAgeMarked.setVisible(false);
            count--;
        }
    }//GEN-LAST:event_PermanentNextAge_imgMouseClicked

    private void PermanentTrade_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PermanentTrade_imgMouseClicked
        if(tradeMarked.isVisible() == false && count <= maxCards) {
            if(count < maxCards) {
                tradeMarked.setVisible(true);
                count++;
            }
        }
        else {
            tradeMarked.setVisible(false);
            count--;
        }
    }//GEN-LAST:event_PermanentTrade_imgMouseClicked

    private void PermanentRecruit_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PermanentRecruit_imgMouseClicked
        if(recruitMarked.isVisible() == false) {
            if(count < maxCards) {
                recruitMarked.setVisible(true);
                count++;
            }
        }
        else {
            recruitMarked.setVisible(false);
            count--;
        }
    }//GEN-LAST:event_PermanentRecruit_imgMouseClicked

    public void setupCards() {
        if(board.getPlayerCulture().compareTo("Egyptian") == 0) {
            PermanentAttack_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/CardPermEgyptAttack.png")));
            PermanentBuild_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/CardPermEgyptBuild.png")));
            PermanentExplore_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/CardPermEgyptExplore.png")));
            PermanentGather_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/CardPermEgyptGather.png")));
            PermanentNextAge_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/CardPermEgyptAge.png")));
            PermanentRecruit_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/CardPermEgyptRecruit.png")));
            PermanentTrade_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/CardPermEgyptTrade.png")));
        }
        else if(board.getPlayerCulture().compareTo("Greek") == 0) {
            PermanentAttack_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/CardPermGreekAttack.png")));
            PermanentBuild_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/CardPermGreekBuild.png")));
            PermanentExplore_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/CardPermGreekExplore.png")));
            PermanentGather_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/CardPermGreekGather.png")));
            PermanentNextAge_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/CardPermGreekAge.png")));
            PermanentRecruit_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/CardPermGreekRecruit.png")));
            PermanentTrade_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/CardPermGreekTrade.png")));
        }
        else if(board.getPlayerCulture().compareTo("Norse") == 0) {
            PermanentAttack_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/CardPermNorseAttack.png")));
            PermanentBuild_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/CardPermNorseBuild.png")));
            PermanentExplore_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/CardPermNorseExplore.png")));
            PermanentGather_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/CardPermNorseGather.png")));
            PermanentNextAge_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/CardPermNorseAge.png")));
            PermanentRecruit_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/CardPermNorseRecruit.png")));
            PermanentTrade_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/CardPermNorseTrade.png")));
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PermanentCardsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PermanentCardsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PermanentCardsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PermanentCardsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PermanentCardsGUI().setVisible(true);
            }
        });
    }

    public void setMaxCards(int maxCards) {
        this.maxCards = maxCards;
    }

    public void setCount(int count) {
        this.count = count;
    }
    
    private int count = 0;
    private int maxCards = 0;
    private BoardController board;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PermanentAttack;
    private javax.swing.JLabel PermanentAttack_img;
    private javax.swing.JPanel PermanentBuild;
    private javax.swing.JLabel PermanentBuild_img;
    private javax.swing.JPanel PermanentExplore;
    private javax.swing.JLabel PermanentExplore_img;
    private javax.swing.JPanel PermanentGather;
    private javax.swing.JLabel PermanentGather_img;
    private javax.swing.JPanel PermanentNextAge;
    private javax.swing.JLabel PermanentNextAge_img;
    private javax.swing.JPanel PermanentRecruit;
    private javax.swing.JLabel PermanentRecruit_img;
    private javax.swing.JPanel PermanentTrade;
    private javax.swing.JLabel PermanentTrade_img;
    private javax.swing.JLabel attackMarked;
    private javax.swing.JLabel buildMarked;
    private javax.swing.JLabel exploreMarked;
    private javax.swing.JLabel gatherMarked;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nextAgeMarked;
    private javax.swing.JLabel recruitMarked;
    private javax.swing.JLabel tradeMarked;
    // End of variables declaration//GEN-END:variables
}
