/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.ageofsettlers;

/**
 *
 * @author SailendraBharadwaj
 */
public class TahTradeCardForEgyptNorseGUI extends javax.swing.JFrame {

    /**
     * Creates new form TahTradeCardForEgyptNorseGUI
     */
    public TahTradeCardForEgyptNorseGUI() {
        this.board = BoardController.getInstance();
        this.egyptPlayer = Egyptian.getInstance();
        this.norsePlayer = Norse.getInstance();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        food = new javax.swing.JRadioButton();
        wood = new javax.swing.JRadioButton();
        gold = new javax.swing.JRadioButton();
        favor = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        food.setText("Food");

        wood.setText("Wood");

        gold.setText("Gold");

        favor.setText("Favor");

        jButton1.setText("Proceed");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(favor)
                    .addComponent(gold)
                    .addComponent(wood)
                    .addComponent(food))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(86, 86, 86))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(food)
                .addGap(32, 32, 32)
                .addComponent(wood)
                .addGap(33, 33, 33)
                .addComponent(gold)
                .addGap(36, 36, 36)
                .addComponent(favor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          if(food.isSelected() == true) {
           if(norsePlayer.getFood() >=2) {
               int norseFood = norsePlayer.getFood() - 2;
               norsePlayer.setFood(norseFood);
               int egyptFood = egyptPlayer.getFood() + 2;
               egyptPlayer.setFood(egyptFood);
               board.updateResources("Norse");
               board.updateResources("Egyptian");
               this.setVisible(false);
           }
           else {
            buildingErrorGUI beGUI = new buildingErrorGUI();
            beGUI.setVisible(true);
           } 
        }
        else if(wood.isSelected() == true) {
             if(norsePlayer.getWood()>=2) {
               int norseWood = norsePlayer.getWood() - 2;
               norsePlayer.setWood(norseWood);
               int egyptWood = egyptPlayer.getWood() + 2;
               egyptPlayer.setWood(egyptWood);
               board.updateResources("Norse");
               board.updateResources("Egyptian");
               this.setVisible(false);
           }
           else {
            buildingErrorGUI beGUI = new buildingErrorGUI();
            beGUI.setVisible(true);
           }  
        }
        else if(gold.isSelected() == true) {
            if(norsePlayer.getGold()>=2) {
               int norseGold = norsePlayer.getGold() - 2;
               norsePlayer.setGold(norseGold);
               int egyptGold = egyptPlayer.getGold() + 2;
               egyptPlayer.setGold(egyptGold);
               board.updateResources("Norse");
               board.updateResources("Egyptian");
               this.setVisible(false);
           }
           else {
            buildingErrorGUI beGUI = new buildingErrorGUI();
            beGUI.setVisible(true);
           }  
            
        }
        else if(favor.isSelected() == true) {
            if(norsePlayer.getFavor()>=2) {
               int norseFavor = norsePlayer.getFavor() - 2;
               norsePlayer.setFavor(norseFavor);
               int egyptFavor = egyptPlayer.getFavor() + 2;
               egyptPlayer.setFavor(egyptFavor);
               board.updateResources("Norse");
               board.updateResources("Egyptian");
               this.setVisible(false);
           }
           else {
            buildingErrorGUI beGUI = new buildingErrorGUI();
            beGUI.setVisible(true);
           }  
        }
          //board.initPlayPermCards();
          board.configureTurnFormation(board.getCurrentPlayerTurn()+1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // 
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TahTradeCardForEgyptNorseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TahTradeCardForEgyptNorseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TahTradeCardForEgyptNorseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TahTradeCardForEgyptNorseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TahTradeCardForEgyptNorseGUI().setVisible(true);
            }
        });
    }
    
    private BoardController board;
    Norse norsePlayer;
    Egyptian egyptPlayer;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton favor;
    private javax.swing.JRadioButton food;
    private javax.swing.JRadioButton gold;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton wood;
    // End of variables declaration//GEN-END:variables
}
