/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.ageofsettlers;

/**
 *
 * @author SailendraBharadwaj
 */
public class TradeHermesGUI extends javax.swing.JFrame {

    /**
     * Creates new form TradeHermesGUI
     */
    public TradeHermesGUI() {
        this.board = BoardController.getInstance();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        playerFoodSelection = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        playerFavorSelection = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        playerWoodSelection = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        playerGoldSelection = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Select any 4 resources for free!");

        playerFoodSelection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        playerFoodSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerFoodSelectionActionPerformed(evt);
            }
        });

        jLabel2.setText("Food:");

        playerFavorSelection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        playerFavorSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerFavorSelectionActionPerformed(evt);
            }
        });

        jLabel3.setText("Favor:");

        playerWoodSelection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        playerWoodSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerWoodSelectionActionPerformed(evt);
            }
        });

        jLabel4.setText("Wood:");

        playerGoldSelection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        playerGoldSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerGoldSelectionActionPerformed(evt);
            }
        });

        jLabel5.setText("Gold:");

        jButton1.setText("Proceed");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(playerFoodSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(playerFavorSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(playerWoodSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2))
                        .addGap(44, 44, 44)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(playerGoldSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerFoodSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(playerFavorSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(playerWoodSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(playerGoldSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playerFoodSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerFoodSelectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playerFoodSelectionActionPerformed

    private void playerFavorSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerFavorSelectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playerFavorSelectionActionPerformed

    private void playerWoodSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerWoodSelectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playerWoodSelectionActionPerformed

    private void playerGoldSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerGoldSelectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playerGoldSelectionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int playerFoodCount = Integer.parseInt((String)playerFoodSelection.getSelectedItem());
        int playerFavorCount = Integer.parseInt((String)playerFavorSelection.getSelectedItem());
        int playerWoodCount = Integer.parseInt((String)playerWoodSelection.getSelectedItem());
        int playerGoldCount = Integer.parseInt((String)playerGoldSelection.getSelectedItem());
        
        int sum1 = playerFoodCount + playerFavorCount + playerWoodCount + playerGoldCount;
        int sum2 = 4;

        if(sum1 == sum2) {
            Greek greekPlayer = Greek.getInstance();
            greekPlayer.setFood(greekPlayer.getFood() + playerFoodCount);
            greekPlayer.setFavor(greekPlayer.getFavor() + playerFavorCount);
            greekPlayer.setWood(greekPlayer.getWood() + playerWoodCount);
            greekPlayer.setGold(greekPlayer.getGold() + playerGoldCount);
              
            board.updateResources("Greek");
            this.setVisible(false);
            tradeGUI tGUI = new tradeGUI();
            tGUI.setVisible(true);
            tGUI.setupTradeGUI("Greek");
        }
        else if(sum1 < sum2) {
            
        }
        else {
            tradeCostErrorGUI tecGUI = new tradeCostErrorGUI();
            tecGUI.setVisible(true);
        }
    }                                                                                                                            

    public void setupTradeCostGUI(String culture) {
        String[] foodCount;
        String[] favorCount;
        String[] woodCount;
        String[] goldCount;
        
        Greek greekPlayer = Greek.getInstance();
        foodCount = new String[greekPlayer.getFood()+1];
        favorCount = new String[greekPlayer.getFavor()+1];
        woodCount = new String[greekPlayer.getWood()+1];
        goldCount = new String[greekPlayer.getGold()+1];
        for(int i = 0; i < foodCount.length; i++) {
            foodCount[i] = String.valueOf(i);
        }
        playerFoodSelection.setModel(new javax.swing.DefaultComboBoxModel(foodCount));
        for(int i = 0; i < favorCount.length; i++) {
            favorCount[i] = String.valueOf(i);
        }
        playerFavorSelection.setModel(new javax.swing.DefaultComboBoxModel(favorCount));
        for(int i = 0; i < woodCount.length; i++) {
            woodCount[i] = String.valueOf(i);
        }
        playerWoodSelection.setModel(new javax.swing.DefaultComboBoxModel(woodCount));
        for(int i = 0; i < goldCount.length; i++) {
           goldCount[i] = String.valueOf(i);
        }
        playerGoldSelection.setModel(new javax.swing.DefaultComboBoxModel(goldCount));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        board.initPlayPermCards();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TradeHermesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TradeHermesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TradeHermesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TradeHermesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TradeHermesGUI().setVisible(true);
            }
        });
    }

    private BoardController board;
    private String playerCulture;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox playerFavorSelection;
    private javax.swing.JComboBox playerFoodSelection;
    private javax.swing.JComboBox playerGoldSelection;
    private javax.swing.JComboBox playerWoodSelection;
    // End of variables declaration//GEN-END:variables
}
